action_id: trunk-share-with-everyone
date: 2025-02-20 07:20:43
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1740036043
full_timestamp:
  nanos: 588379000
  seconds: 1740036043
trunk_version: 1.22.10
